# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.12
COPY --from=ghcr.io/astral-sh/uv:0.7.13 /uv /uvx /bin/

RUN uv pip install --system \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY docker/dagster.yaml docker/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
