FROM python:3.12

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

WORKDIR /opt/dagster/app

COPY requirements.txt /opt/dagster/app/requirements.txt
COPY footballpace /opt/dagster/app/footballpace

RUN pip install -r requirements.txt

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "footballpace"]
