# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.14-slim-trixie AS builder
COPY --from=ghcr.io/astral-sh/uv:0.11.11 /uv /uvx /bin/
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
ENV UV_PYTHON_DOWNLOADS=0

WORKDIR /opt/dagster/app
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --only-group dagster

FROM python:3.14-slim-trixie

COPY --from=builder /opt/dagster/app/.venv /opt/dagster/app/.venv
ENV PATH="/opt/dagster/app/.venv/bin:$PATH"

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

COPY docker/dagster.yaml docker/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
